{
 "title": "Questions",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Controller Action Error Rates",
   "type": "gauge",
   "description": "Which controllers fail most frequently?",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "step" ] } },
   "targets": [
    {
     "expr": "rate(chatapi_controller_errors_total{action=\"GetMessages\"}[$__rate_interval])",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "rate(chatapi_controller_errors_total{action=\"PostMessage\"}[$__rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Slowest EFCore Translated Queries",
   "type": "table",
   "description": "What are the slowest queries?",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "eab2b38a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "ChatApi" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"ChatApi\" && name=\"chatdb\"} | select(span.db.statement)",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Process Memory Usage ",
   "type": "timeseries",
   "description": "How is our server doing? What times does usage spike?",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{exported_job=\"ChatApi\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}