{
 "title": "Main Dashboard",
 "time": { "from": "2024-01-18T11:50:03.755Z", "to": "2024-01-20T11:50:03.755Z" },
 "panels": [
  {
   "title": "Total Messages Sent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chatapi_messages_sent_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chatapi_daily_active_users_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "When Are Messages Sent",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"ChatApi\"} |= `Message posted by` | json"
    }
   ]
  }
 ]
}