{
 "title": "Image Redundancy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Redundancy Info Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ChatImageRedundancy\"} |= `Information`"
    }
   ]
  },
  {
   "title": "Redundancy Error Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ChatImageRedundancy\"} |= `Error`"
    }
   ]
  },
  {
   "title": "# of Non-Redundant vs # of Total Images",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chatimageredundancy_total_nonredundant_Number_of_non_redundant_images_uploaded",
     "legendFormat": "__auto"
    },
    {
     "expr": "chatimageredundancy_total_upload_Number_of_images_uploaded",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}