{
 "title": "Raft Election Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node1",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"Node1\"} |= `NodeService` | json | line_format \"{{.body}}\"\r\n"
    }
   ]
  },
  {
   "title": "Node2",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"Node2\"} |= `NodeService` | json | line_format \"{{.body}}\"\r\n\r\n"
    }
   ]
  },
  {
   "title": "Node3",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"Node3\"} |= `NodeService` | json | line_format \"{{.body}}\"\r\n"
    }
   ]
  },
  {
   "title": "Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"RaftGateway\"} |= `` | json | line_format \"{{.body}}\""
    }
   ]
  },
  {
   "title": "Node Storage Endpoint Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{job=~\"Node1|Node2|Node3\"} |= `` | json | line_format `{{.body}}`"
    }
   ]
  }
 ]
}