x-node_base: &node_base
  build:
    context: ./src/Raft/
    dockerfile: node.Dockerfile
  develop:
    watch:
      - action: rebuild
        path: ./src/Raft

x-node-environment: &node-environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  TZ: America/Denver

services:
  nginx:
    depends_on:
      - shop 
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./ops/dev/nginx.conf:/etc/nginx/conf.d/default.conf

  shop:
    build:
      context: ./src/Raft/
      dockerfile: shop.Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      TZ: America/Denver
    develop:
      watch:
        - action: rebuild
          path: ./src/Raft

  gateway:
    build:
      context: ./src/Raft/
      dockerfile: gateway.Dockerfile
      target: development
    environment:
      MicroServiceOptions__NodeCount: 3
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      TZ: America/Denver
    develop:
      watch:
        - action: rebuild
          path: ./src/Raft

  node1:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 1
      ObservabilityOptions__ServiceName: Node1

  node2:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 2
      ObservabilityOptions__ServiceName: Node2

  node3:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 3
      ObservabilityOptions__ServiceName: Node3
