include:
  - ./ops/dev/observability/docker-compose.yml

x-dotnet_sync: &dotnet_sync
  develop:
    watch:
      - action: sync
        path: ./src/Raft
        target: ./src/
        ignore:
          - ./src/Raft/Raft.Gateway/bin
          - ./src/Raft/Raft.Gateway/obj
          - ./src/Raft/Raft.Node/bin
          - ./src/Raft/Raft.Node/obj
          - ./src/Raft/Raft.Observability/bin
          - ./src/Raft/Raft.Observability/obj
          - ./src/Raft/Raft.Shop/Raft.Shop/bin
          - ./src/Raft/Raft.Shop/Raft.Shop/obj
          - ./src/Raft/Raft.Shop/Raft.Shop.Client/bin
          - ./src/Raft/Raft.Shop/Raft.Shop.Client/obj

x-node_base: &node_base
  build:
    context: ./src/Raft/
    dockerfile: node.Dockerfile
    target: development
  <<: *dotnet_sync

x-node-environment: &node-environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  TZ: America/Denver

services:
  nginx:
    depends_on:
      - shop
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./ops/dev/nginx.conf:/etc/nginx/conf.d/default.conf

  shop:
    build:
      context: ./src/Raft/
      dockerfile: shop.Dockerfile
      target: development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    <<: *dotnet_sync

  gateway:
    build:
      context: ./src/Raft/
      dockerfile: gateway.Dockerfile
      target: development
    environment:
      MicroServiceOptions__NodeCount: 3
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ObservabilityOptions__CollectorUrl: http://collector:4317
      TZ: America/Denver
    <<: *dotnet_sync

  node1:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 1
      ObservabilityOptions__ServiceName: Node1

  node2:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 2
      ObservabilityOptions__ServiceName: Node2

  node3:
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__NodeCount: 3
      MicroServiceOptions__Identifier: 3
      ObservabilityOptions__ServiceName: Node3
