
version: "3.9"

include:
  - compose.nodebase.yml


services:
  node3:
    container_name: w-node3
    <<: *node_base
    environment:
      <<: *node-environment
      MicroServiceOptions__Identifier: 3
      ObservabilityOptions__ServiceName: Node3
    profiles:
      - worker

networks:
  w-overlay:
    name: w-overlay
    external: true