services:
  collector:
    container_name: dc-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ../shared/config-files/otel-collector.yaml:/etc/otel-collector.yaml
    # ports:
    # - 1888:1888 # pprof extension
    # - 13133:13133 # health_check extension
    # - 55679:55679 # zpages extension
    # - 8888:8888 # Prometheus metrics exposed by the collector
    # - 8889:8889 # Prometheus exporter metrics
    # - 4317:4317 # OTLP gRPC receiver
    # - 4318:4318 # OTLP http receiver
    depends_on:
      - tempo
      - prometheus
      - loki

  tempo:
    container_name: dc-tempo
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    # ports:
    # - "3200:3200" # tempo
    # - "4317" # otlp grpc
    volumes:
      - ../shared/config-files/tempo.yaml:/etc/tempo.yaml
      - dc-tempo-data:/tmp/tempo

  prometheus:
    container_name: dc-prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:8080"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    # ports:
    #   - "8080:8080"
    environment:
      - config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../shared/config-files/prometheus.yaml:/etc/prometheus/prometheus.yml
      - dc-prometheus-data:/prometheus

  loki:
    container_name: dc-loki
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - dc-loki-data:/loki

  grafana:
    container_name: dc-grafana
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    volumes:
      - ../shared/config-files/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../shared/config-files/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ../shared/dashboards:/var/lib/grafana/dashboards
      - ../shared/config-files/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - tempo
      - prometheus
      - loki
      - collector

volumes:
  dc-loki-data:
  dc-tempo-data:
  dc-prometheus-data:
  dc-postgres-data:
