
x-node_base: &node_base
  build:
    context: ../../src/Raft/
    dockerfile: ./Raft.Node/Dockerfile
    target: final
  networks:
    - w-overlay

x-node-environment: &node-environment
  ASPNETCORE_URLS: http://+:8080
  ObservabilityOptions__CollectorUrl: http://collector:4317
  MicroServiceOptions__NodeCount: 3
  MicroServiceOptions__NodeServiceName: node
  ApiOptions__NodeServicePort: 8080
  ApiOptions__LogMessageIntervalSeconds: 600
  TZ: America/Denver