name: Deploy

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    uses: ./.github/workflows/format.yml

  tests:
    needs: format
    uses: ./.github/workflows/test.yml

  deploy-application:
    needs: tests
    runs-on: [alex-office5]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: redeploy application
        run: |
          cd ops/prod
          docker compose pull
          docker compose up -d --build --profile manager

  deploy-other-node:
    needs: deploy-application
    runs-on: [alex-office4]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: redeploy application
        run: |
          cd ops/prod
          docker compose pull
          docker compose up -d --build --profile worker
