name: Dotnet Format

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dotnet-format:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Format
        run: |
          cd src/Raft
          docker build -t raft_format .
          docker run -i --rm raft_format dotnet format --verify-no-changes --verbosity diagnostic --no-restore
