name: Dotnet Format

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Only run if dotnet changes
        id: check_changes
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            dotnet:
              - 'src/Chat/**'

      - name: Format
        if: steps.check_changes.outputs.dotnet == 'true'
        run: |
          cd src/Chat
          docker build --no-cache -t chat_format -f Dockerfile .
          docker run -i --rm chat_format dotnet format --verify-no-changes --verbosity diagnostic
