name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: |
          cd src/Raft
          docker build -t raft_tests .
          docker run -i --rm raft_tests dotnet test 
