name: Dotnet Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies and run tests
        run: |
          cd src/Raft
          dotnet test
